#!/usr/bin/env python
# Copyright 2014-2021 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: James McClain <jdmcclain47@gmail.com>
#         Hong-Zhou Ye <hzyechem@gmail.com>
#


'''
kpoint-adapted unrestricted MP2
t2 = (t2aa, t2ab, t2bb)
t2aa/ab/bb[i,j,a,b] = <ij|ab> / D_ij^ab
'''


import numpy as np
import h5py

from pyscf import lib
from pyscf.lib import logger, einsum
from pyscf.pbc.mp import kmp2
from pyscf.pbc import df
from pyscf.pbc.lib import kpts_helper
from pyscf.pbc.mp.kmp2 import _frozen_sanity_check
from pyscf.lib.parameters import LARGE_DENOM
from pyscf import __config__

WITH_T2 = getattr(__config__, 'mp_ump2_with_t2', True)

def kernel(mp, mo_energy, mo_coeff, eris=None, with_t2=WITH_T2, verbose=None):
    """Computes k-point UMP2 energy.

    Args:
        mp (KMP2): an instance of KMP2
        mo_energy (list): a nested list of numpy.ndarray. Each array contains MO
                          energies of shape (Nmo,) for one spin and kpt
        mo_coeff (list): a nested list of numpy.ndarray. Each array contains MO
                         coefficients of shape (Nao, Nmo) for one spin and kpt
        eris: generated by mp.ao2mo()
        verbose (int, optional): level of verbosity. Defaults to logger.NOTE (=3).
        with_t2 (bool, optional): whether to compute t2 amplitudes. Defaults to WITH_T2 (=True).

    Returns:
        KMP2 energy and t2 amplitudes (=None if with_t2 is False)
    """
    cput0 = (logger.process_clock(), logger.perf_counter())
    log = logger.new_logger(mp, verbose)

    nmo = mp.nmo
    nocc = mp.nocc
    nvir = tuple([nmo[s] - nocc[s] for s in [0,1]])
    noccmax = max(nocc)
    nvirmax = max(nvir)
    nkpts = mp.nkpts
    with_df_ints = mp.with_df_ints

    mp._memory_sanity_check(with_t2)

    if with_t2:
        t2aa = np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[0], nvir[0], nvir[0]),
                        dtype=complex)
        t2ab = np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[1], nvir[0], nvir[1]),
                        dtype=complex)
        t2bb = np.zeros((nkpts, nkpts, nkpts, nocc[1], nocc[1], nvir[1], nvir[1]),
                        dtype=complex)
        t2 = (t2aa,t2ab,t2bb)
    else:
        t2 = None

    if eris is None: eris = mp.ao2mo(mo_coeff=mo_coeff)

    kconserv = mp.khelper.kconserv

    if mo_energy is None: mo_energy = eris.mo_energy
    mo_e_o = [[mo_energy[s][k][:nocc[s]] for k in range(nkpts)] for s in [0,1]]
    mo_e_v = [[mo_energy[s][k][nocc[s]:] for k in range(nkpts)] for s in [0,1]]

    # Get location of non-zero/padded elements in occupied and virtual space
    nonzero_opadding, nonzero_vpadding = padding_k_idx(mp, kind="split")

    # helper functions
    def get_eia(s,ki,ka):
        # Remove zero/padded elements from denominator
        eia = LARGE_DENOM * np.ones((nocc[s], nvir[s]), dtype=mo_energy[s][0].dtype)
        n0_ovp_ia = np.ix_(nonzero_opadding[s][ki], nonzero_vpadding[s][ka])
        eia[n0_ovp_ia] = (mo_e_o[s][ki][:,None] - mo_e_v[s][ka])[n0_ovp_ia]
        return eia
    def _contract1_ss(is12, kijab, shls_slice, eia, ejb, gdi, gxi=None):
        p0,p1 = shls_slice
        ejab = lib.direct_sum('ia+jb->ijab', eia[p0:p1], ejb)
        t2i = gdi.conj() / ejab
        e_this = einsum('ijab,ijab->', t2i, gdi)
        if with_t2:
            t2[is12][kijab[0],kijab[1],kijab[2],p0:p1] = t2i
        if gxi is None:
            e_this -= einsum('ijab,ijba->', t2i, gdi)
        else:
            e_this -= einsum('ijab,ijba->', t2i, gxi) * 2. # (ka,kb) swap
            t2i = None
            t2i = gxi.conj() / ejab.transpose(0,1,3,2)
            e_this += einsum('ijab,ijab->', t2i, gxi)
            if with_t2:
                t2[is12][kijab[0],kijab[1],kijab[3],p0:p1] = t2i
        t2i = ejab = None
        return e_this.real * 0.5
    def _contract1_os(is12, kijab, shls_slice, eia, ejb, gdi, gxi=None):
        p0,p1 = shls_slice
        ejab = lib.direct_sum('ia+jb->ijab', eia[p0:p1], ejb)
        t2i = gdi.conj() / ejab
        e_this = einsum('ijab,ijab->', t2i, gdi)
        if with_t2:
            t2[is12][kijab[0],kijab[1],kijab[2],p0:p1] = t2i
        if gxi is not None:
            t2i = None
            t2i = gxi.conj() / ejab.transpose(0,1,3,2)
            e_this += einsum('ijab,ijab->', t2i, gxi)
            if with_t2:
                t2[is12][kijab[0],kijab[1],kijab[3],p0:p1] = t2i
        t2i = ejab = None
        return e_this.real * 0.5

    # compute
    mem_avail = mp.max_memory - lib.current_memory()[0]
    # 4 ovv-type tensors: gdi, gxi, ejab, t2i
    blksize = int(np.floor(mem_avail*0.7 / (noccmax*nvirmax**2.*4 * 16/1e6)))
    cache_eris = not (mp.with_df_ints or mp.less_mem)
    cput1 = (logger.process_clock(), logger.perf_counter())
    emp2_ss = emp2_os = 0.
    for ki in range(nkpts):
        for kj in range(nkpts):
            kblist = [kconserv[ki,ka,kj] for ka in range(nkpts)]
            done = {(ka,kblist[ka]):False for ka in range(nkpts)}
            for ka in range(nkpts):
                kb = kblist[ka]
                if done[(ka,kb)] and done[(kb,ka)]:
                    continue

                kijab = (ki,kj,ka,kb)
                eia = [get_eia(s,ki,ka) for s in [0,1]]
                ejb = [get_eia(s,kj,kb) for s in [0,1]]

                for is12,s12 in enumerate([(0,0),(0,1),(1,1)]):
                    s1,s2 = s12
                    p1 = 0
                    for gdi,gxi in eris.loop_oovv(s12, kijab, blksize=blksize,
                                                  cache_eris=cache_eris):
                        p0 = p1
                        p1 = p0 + gdi.shape[0]

                        if s1 == s2:
                            emp2_ss += _contract1_ss(is12, kijab, (p0,p1), eia[s1],
                                                     ejb[s2], gdi, gxi)
                        else:
                            emp2_os += _contract1_os(is12, kijab, (p0,p1), eia[s1],
                                                     ejb[s2], gdi, gxi) * 2.

                        gdi = gxi = None

                done[(ka,kb)] = done[(kb,ka)] = True

            cput1 = log.timer_debug1('(ki,kj) = (%d,%d)'%(ki,kj), *cput1)

    log.timer(mp.__class__.__name__, *cput0)

    emp2_ss /= nkpts
    emp2_os /= nkpts
    emp2 = emp2_ss + emp2_os

    return emp2, t2, emp2_ss, emp2_os

def padding_k_idx(mp, kind="split"):
    """For a description, see `padding_k_idx` in kmp2.py.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        kind (str): either "split" (occupied and virtual spaces are split) or "joint"
        (occupied and virtual spaces are the joint;

    Returns:
        Two lists corresponding to the occupied and virtual spaces for kind="split".
        Each list contains integer arrays with indexes pointing to actual non-zero
        entries in the padded vector/matrix/tensor. If kind="joint", a single list of
        arrays is returned corresponding to the entire MO space.
    """
    if kind not in ("split", "joint"):
        raise ValueError("The 'kind' argument must be one of 'split', 'joint'")

    if kind == "split":
        indexes_oa = []
        indexes_va = []
        indexes_ob = []
        indexes_vb = []
    else:
        indexesa = []
        indexesb = []

    dense_oa, dense_ob = mp.nocc
    dense_nmoa, dense_nmob = mp.nmo
    dense_va = dense_nmoa - dense_oa
    dense_vb = dense_nmob - dense_ob

    nocca_per_kpt, noccb_per_kpt = np.asarray(get_nocc(mp, per_kpoint=True))
    nmoa_per_kpt, nmob_per_kpt = np.asarray(get_nmo(mp, per_kpoint=True))

    # alpha spin
    for k_oa, k_nmoa in zip(nocca_per_kpt, nmoa_per_kpt):
        k_va = k_nmoa - k_oa
        if kind == "split":
            indexes_oa.append(np.arange(k_oa))
            indexes_va.append(np.arange(dense_va - k_va, dense_va))
        else:
            indexesa.append(np.concatenate((
                np.arange(k_oa),
                np.arange(dense_nmoa - k_va, dense_nmoa),
            )))

    # beta spin
    for k_ob, k_nmob in zip(noccb_per_kpt, nmob_per_kpt):
        k_vb = k_nmob - k_ob
        if kind == "split":
            indexes_ob.append(np.arange(k_ob))
            indexes_vb.append(np.arange(dense_vb - k_vb, dense_vb))
        else:
            indexesb.append(np.concatenate((
                np.arange(k_ob),
                np.arange(dense_nmob - k_vb, dense_nmob),
            )))

    if kind == "split":
        # return [indexes_oa, indexes_va], [indexes_ob, indexes_vb]
        return [indexes_oa, indexes_ob], [indexes_va, indexes_vb]
    else:
        return indexesa, indexesb


def padded_mo_energy(mp, mo_energy):
    """
    Pads energies of active MOs.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        mo_energy (ndarray): original non-padded molecular energies;

    Returns:
        Padded molecular energies.
    """
    frozen_mask = get_frozen_mask(mp)
    padding_convention = padding_k_idx(mp, kind="joint")
    nkpts = mp.nkpts

    result = (np.zeros((nkpts, mp.nmo[0]), dtype=mo_energy[0][0].dtype),
              np.zeros((nkpts, mp.nmo[1]), dtype=mo_energy[1][0].dtype))
    for spin in [0, 1]:
        for k in range(nkpts):
            result[spin][np.ix_([k], padding_convention[k])] = \
                                    mo_energy[spin][k][frozen_mask[spin][k]]

    return result


def padded_mo_coeff(mp, mo_coeff):
    """
    Pads coefficients of active MOs.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        mo_coeff (ndarray): original non-padded molecular coefficients;

    Returns:
        Padded molecular coefficients.
    """
    frozen_mask = get_frozen_mask(mp)
    padding_convention = padding_k_idx(mp, kind="joint")
    nkpts = mp.nkpts

    result = (np.zeros((nkpts, mo_coeff[0][0].shape[0], mp.nmo[0]),
                       dtype=mo_coeff[0][0].dtype),
              np.zeros((nkpts, mo_coeff[1][0].shape[0], mp.nmo[1]),
                       dtype=mo_coeff[1][0].dtype))
    for spin in [0, 1]:
        for k in range(nkpts):
            result[spin][np.ix_([k], np.arange(result[spin].shape[1]),
                         padding_convention[spin][k])] = \
                                    mo_coeff[spin][k][:,frozen_mask[spin][k]]

    return result


def _is_arraylike(x):
    return isinstance(x, (tuple, list, np.ndarray))


def get_nocc(mp, per_kpoint=False):
    '''Number of occupied orbitals for k-point calculations.

    Number of occupied orbitals for use in a calculation with k-points, taking into
    account frozen orbitals.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        per_kpoint (bool, optional): True returns the number of occupied
            orbitals at each k-point.  False gives the max of this list.

    Returns:
        nocc (int, list of int): Number of occupied orbitals. For return type, see description of arg
            `per_kpoint`.

    Notes:
        For specifying frozen orbitals inside mp, the following options are accepted:

            +=========================+========================================+===============================+
            | Argument (Example)      | Argument Meaning                       | Example Meaning               |
            +=========================+========================================+===============================+
            | int (1)                 | Freeze the same number of orbitals     | Freeze one (lowest) orbital   |
            |                         | regardless of spin and/or kpt          | for all kpts and spin cases   |
            +-------------------------+----------------------------------------+-------------------------------+
            | 2-tuple of list of int  | inner list: List of orbitals indices   | Freeze the orbitals [0,4] for |
            | ([0, 4], [0, 5, 6])     |   to freeze at all kpts                | spin0, and orbitals [0,5,6]   |
            |                         | outer list: Spin index                 | for spin1 at all kpts         |
            +-------------------------+----------------------------------------+-------------------------------+
            | list(2) of list of list | inner list: list of orbital indices to | Freeze orbital 0 for spin0 at |
            | ([[0,],[]],             |   freeze at each kpt for given spin    | kpt0, and freeze orbital 0,1  |
            |  [[0,1],[4]])           | outer list: spin index                 | for spin1 at kpt0 and orbital |
            |                         |                                        | 4 at kpt1                     |
            +-------------------------+----------------------------------------+-------------------------------+

    '''
    for spin in [0,1]:
        for i, moocc in enumerate(mp.mo_occ[spin]):
            if np.any(moocc % 1 != 0):
                raise RuntimeError(
                    "Fractional occupation numbers encountered @ kp={:d}: {}.  "
                    "This may have been caused by smearing of occupation numbers "
                    "in the mean-field calculation. If so, consider executing "
                    "mf.smearing_method = False; mf.mo_occ = mf.get_occ() prior "
                    "to calling this".format(i, moocc))
    if mp._nocc is not None:
        return mp._nocc

    elif mp.frozen is None:
        nocc = [[np.count_nonzero(mp.mo_occ[0][k] > 0) for k in range(mp.nkpts)],
                [np.count_nonzero(mp.mo_occ[1][k] > 0) for k in range(mp.nkpts)]]

    elif isinstance(mp.frozen, (int, np.integer)):
        nocc = [0]*2
        for spin in [0,1]:
            nocc[spin] = [(np.count_nonzero(mp.mo_occ[spin][k] > 0) - mp.frozen) for k in range(mp.nkpts)]

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (int, np.integer))):  # case example: ([0, 4], [0, 5, 6])
        nocc = [0]*2
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            nocc_spin = []
            for ikpt in range(mp.nkpts):
                max_occ_idx = np.max(np.where(mp.mo_occ[spin][ikpt] > 0))
                frozen_nocc = np.sum(np.array(mp.frozen[spin]) <= max_occ_idx)
                nocc_spin.append(np.count_nonzero(mp.mo_occ[spin][ikpt]) - frozen_nocc)
            nocc[spin] = nocc_spin

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (list, np.ndarray))):  # case example: ([[0,],[]], [[0,1],[4]])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            nkpts = len(mp.frozen[spin])
            if nkpts != mp.nkpts:
                raise RuntimeError('Frozen list has a different number of k-points (length) than passed in'
                                   'mean-field/correlated calculation.  \n\nCalculation nkpts = %d, frozen'
                                   'list = %s (length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        nocc = [0]*2
        for spin in [0,1]:
            [_frozen_sanity_check(frozen, mo_occ, ikpt)
             for ikpt, frozen, mo_occ in zip(range(nkpts), mp.frozen[spin], mp.mo_occ[spin])]
            nocc_spin = []
            for ikpt, frozen in enumerate(mp.frozen[spin]):
                max_occ_idx = np.max(np.where(mp.mo_occ[spin][ikpt] > 0))
                frozen_nocc = np.sum(np.array(frozen) <= max_occ_idx)
                nocc_spin.append(np.count_nonzero(mp.mo_occ[spin][ikpt]) - frozen_nocc)
            nocc[spin] = nocc_spin
    else:
        raise NotImplementedError('No known conversion for frozen %s' % mp.frozen)

    for spin in [0,1]:
        assert any(np.array(nocc[spin]) > 0), (
            'Must have occupied orbitals (spin=%d)! \n\nnocc %s\nfrozen %s\nmo_occ %s' %
            (spin, nocc, mp.frozen, mp.mo_occ))

    nocca, noccb = nocc
    if not per_kpoint:
        nocca = np.amax(nocca)
        noccb = np.amax(noccb)

    return nocca, noccb


def get_nmo(mp, per_kpoint=False):
    '''Number of orbitals for k-point calculations.

    Number of orbitals for use in a calculation with k-points, taking into account
    frozen orbitals.

    Note:
        If `per_kpoint` is False, then the number of orbitals here is equal to max(nocc) + max(nvir),
        where each max is done over all k-points.  Otherwise the number of orbitals is returned
        as a list of number of orbitals at each k-point.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        per_kpoint (bool, optional): True returns the number of orbitals at each k-point.
            For a description of False, see Note.

    Returns:
        nmo (int, list of int): Number of orbitals. For return type, see description of arg
            `per_kpoint`.

    '''
    if mp._nmo is not None:
        return mp._nmo

    nmo = [0, 0]
    if isinstance(mp.frozen, (int, np.integer)):
        for spin in [0,1]:
            nmo[spin] = [len(mp.mo_occ[spin][k]) - mp.frozen for k in range(mp.nkpts)]

    elif mp.frozen is None:
        nmo = [[len(mp.mo_occ[0][k]) for k in range(mp.nkpts)],
               [len(mp.mo_occ[1][k]) for k in range(mp.nkpts)]]

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (int, np.integer))):  # case example: ([0, 4], [0, 5, 6])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            nmo[spin] = [len(mp.mo_occ[spin][ikpt]) - len(mp.frozen[spin]) for ikpt in range(mp.nkpts)]

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (list, np.ndarray))):  # case example: ([[0,],[]], [[0,1],[4]])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            nkpts = len(mp.frozen[spin])
            if nkpts != mp.nkpts:
                raise RuntimeError('Frozen list has a different number of k-points (length) than passed in'
                                   'mean-field/correlated calculation.  \n\nCalculation nkpts = %d, frozen'
                                   'list = %s (length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin][ikpt], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            nmo[spin] = [len(mp.mo_occ[spin][ikpt]) - len(mp.frozen[spin][ikpt]) for ikpt in range(nkpts)]

    else:
        raise NotImplementedError('No known conversion for frozen %s' % mp.frozen)

    for spin in [0,1]:
        assert all(np.array(nmo[spin]) > 0), (
            'Must have a positive number of orbitals! (spin=%d)'
            '\n\nnmo %s\nfrozen %s\nmo_occ %s' % (spin, nmo, mp.frozen, mp.mo_occ))

    nmoa, nmob = nmo
    if not per_kpoint:
        # Depending on whether there are more occupied bands, we want to make sure    that
        # nmo has enough room for max(nocc) + max(nvir) number of orbitals for        occupied
        # and virtual space
        nocca, noccb = mp.get_nocc(per_kpoint=True)
        nmoa = np.amax(nocca) + np.max(np.array(nmoa) - np.array(nocca))
        nmob = np.amax(noccb) + np.max(np.array(nmob) - np.array(noccb))

    return nmoa, nmob


def get_frozen_mask(mp):
    '''Boolean mask for orbitals in k-point post-HF method.

    Creates a boolean mask to remove frozen orbitals and keep other orbitals for post-HF
    calculations.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.

    Returns:
        moidx (list of :obj:`ndarray` of `np.bool`): Boolean mask of orbitals to include.

    '''
    moidx = [[np.ones(x.size, dtype=np.bool) for x in mp.mo_occ[s]] for s in [0,1]]

    if mp.frozen is None:
        pass

    elif isinstance(mp.frozen, (int, np.integer)):
        for spin in [0,1]:
            for idx in moidx[spin]:
                idx[:mp.frozen] = False

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (int, np.integer))):  # case example: ([0, 4], [0, 5, 6])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            for ikpt, kpt_occ in enumerate(moidx[spin]):
                kpt_occ[mp.frozen[spin]] = False

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (list, np.ndarray))):  # case example: ([[0,],[]], [[0,1],[4]])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            nkpts = len(mp.frozen[spin])
            if nkpts != mp.nkpts:
                raise RuntimeError('Frozen list has a different number of k-points (length) than passed in'
                                   'mean-field/correlated calculation.  \n\nCalculation nkpts = %d, frozen'
                                   'list = %s (length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin][ikpt], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            for ikpt, kpt_occ in enumerate(moidx[spin]):
                kpt_occ[mp.frozen[spin][ikpt]] = False
    else:
        raise NotImplementedError('No known conversion for frozen %s' % mp.frozen)

    return moidx


def _add_padding(mp, mo_coeff, mo_energy):
    mo_coeff = _add_padding_mo_coeff(mp, mo_coeff)
    mo_energy = _add_padding_mo_coeff(mp, mo_energy)
    return mo_coef, mo_energy

def _add_padding_mo_coeff(mp, mo_coeff):
    nmo = mp.nmo
    if not (np.all([x.shape[1] == nmo[0] for x in mo_coeff[0]]) and
            np.all([x.shape[1] == nmo[1] for x in mo_coeff[1]])):
        mo_coeff = padded_mo_coeff(mp, mo_coeff)
    return mo_coeff

def _add_padding_mo_energy(mp, mo_energy):
    nmo = mp.nmo
    if not (np.all([x.shape[0] == nmo[0] for x in mo_energy[0]]) and
            np.all([x.shape[0] == nmo[1] for x in mo_energy[1]])):
        mo_energy = padded_mo_energy(mp, mo_energy)
    return mo_energy


class KUMP2(kmp2.KMP2):
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask

    def kernel(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=WITH_T2):
        if self.verbose >= logger.WARN:
            self.check_sanity()
        self.dump_flags()

        if mo_coeff is None: mo_coeff = self.mo_coeff

        if eris is None:
            eris = self.ao2mo(mo_coeff)

        self.e_hf = getattr(eris, 'e_hf', None)
        if self.e_hf is None:
            self.e_hf = self._scf.e_tot

        self.e_corr, self.t2, self.e_corr_ss, self.e_corr_os = \
                    kernel(self, mo_energy, mo_coeff, eris, with_t2)

        self._finalize()

        return self.e_corr, self.t2

    def _memory_sanity_check(self, with_t2):
        nocc = self.nocc
        nvir = [self.nmo[s] - nocc[s] for s in [0,1]]
        noccmax = max(nocc)
        nvirmax = max(nvir)
        nkpts = len(self.kpts)
        with_df_ints = self.with_df_ints

        mem_usage = 2*noccmax*nvirmax**2 * 16/1e6 # ejab and t2i
        if not (with_df_ints or self.less_mem):
            mem_usage += 2*(noccmax*nvirmax)**2 * 16/1e6 # (ia|jb) and (ib|ja)
        if with_t2:
            nov = [nocc[s]*nvir[s] for s in [0,1]]
            mem_usage += (nkpts**3 * (nov[0]**2+nov[1]**2+nov[0]*nov[1])) * 16/1e6

        mem_avail = self.max_memory - lib.current_memory()[0]
        if mem_usage > mem_avail:
            logger.error(self, 'Insufficient memory! MP2 memory usage %.1f MB '
                         '(currently available %.1f MB)', mem_usage, mem_avail)
            raise MemoryError

    def ao2mo(self, mo_coeff=None):
        log = logger.new_logger(self)
        nao = self.mol.nao_nr()
        nocc = self.nocc
        nvir = [self.nmo[s] - nocc[s] for s in [0,1]]
        noccmax = max(nocc)
        nvirmax = max(nvir)
        nkpts = len(self.kpts)
        with_df_ints = self.with_df_ints
        if mo_coeff is None: mo_coeff = self.mo_coeff

        mem_usage = 2*noccmax*nvirmax**2 * 16/1e6 # ejab and t2i
        if with_df_ints:
            mydf = self._scf.with_df
            if mydf.auxcell is None:
                # Calculate naux based on precomputed GDF integrals
                naux = mydf.get_naoaux()
            else:
                naux = mydf.auxcell.nao_nr()
            nov = [nocc[s]*nvir[s] for s in [0,1]]
            mem_usage += (nkpts**2 * naux * sum(nov)) * 16 / 1e6
            mem_usage += naux * nao**2 * 16 / 1e6 # for loading Lpq of 1 kpt-pair in xform
            mem_avail = self.max_memory - lib.current_memory()[0]
            log.debug('est mem use for DF integral xform %.1f MB '
                      '(currently available %.1f MB)', mem_usage, mem_avail)
            if mem_usage > mem_avail:
                log.info('Holding DF integrals outcore.')
                return _make_df_eris_outcore(self, mo_coeff)
            else:
                log.info('Holding DF integrals incore.')
                return _make_df_eris_incore(self, mo_coeff)
        else:
            return _make_eris_incore(self, mo_coeff)

class _MP2ERIS_INCORE(kmp2._MP2ERIS_INCORE):

    def _common_init_(self, mp, mo_coeff=None):
        from pyscf.pbc.lib.kpts_helper import gamma_point
        self.kpts = mp.kpts
        nkpts = len(self.kpts)
        self.dtype = np.double if gamma_point(self.kpts) else np.complex128
        self.dsize = 8 if gamma_point(self.kpts) else 16

        if mo_coeff is None:
            mo_coeff = mp.mo_coeff
        if mo_coeff is None:
            raise RuntimeError('mo_coeff, mo_energy are not initialized.\n'
                               'You may need to call mf.kernel() to generate them.')

        self.mo_coeff = _add_padding_mo_coeff(mp, mo_coeff)

        if mo_coeff is mp._scf.mo_coeff and mp._scf.converged:
            # The canonical MP2 from a converged SCF result. Rebuilding fock
            # and e_hf can be skipped
            self.mo_energy = _add_padding_mo_energy(mp, mp._scf.mo_energy)
            self.fock = [np.array([np.diag(self.mo_energy[s][k])
                                   for k in range(nkpts)]) for s in [0,1]]
            self.e_hf = mp._scf.e_tot
        else:
            dm = mp._scf.make_rdm1(mo_coeff, mp.mo_occ)
            vhf = mp._scf.get_veff(mp.mol, dm)
            fockao = mp._scf.get_fock(vhf=vhf, dm=dm)
            self.fock = [np.array([np.linalg.multi_dot(self.mo_coeff[s][k].conj().T,
                                                       fockao[s][k], self.mo_coeff[s][k])
                                   for k in range(nkpts)]) for s in [0,1]]
            self.e_hf = mp._scf.energy_tot(dm=dm, vhf=vhf)
            self.mo_energy = [np.array([self.fock[s][k].diagonal().real
                                        for k in range(nkpts)]) for s in [0,1]]

        self.nocc = mp.nocc
        self.nmo = mp.nmo
        self._fao2mo = mp._scf.with_df.ao2mo

        return self

    def get_oovv(self, s12, kijab, shls_slice_i=None):
        s1,s2 = s12
        ki,kj,ka,kb = kijab
        kpts = self.kpts
        mo_coeff = self.mo_coeff
        nocc = self.nocc
        if shls_slice_i is None:
            shls_slice_i = (0, nocc[s1])

        orbo_i = mo_coeff[s1][ki][:,shls_slice_i[0]:shls_slice_i[1]]
        orbo_j = mo_coeff[s2][kj][:,:nocc[s2]]
        orbv_a = mo_coeff[s1][ka][:,nocc[s1]:]
        orbv_b = mo_coeff[s2][kb][:,nocc[s2]:]
        return self.fao2mo((orbo_i,orbv_a,orbo_j,orbv_b),
                           (kpts[ki],kpts[ka],kpts[kj],kpts[kb]))

    def loop_oovv(self, s12, kijab, swap_kakb=True, cache_eris=False, max_memory=2000,
                  blksize=None):
        ki,kj,ka,kb = kijab
        kijba = (ki,kj,kb,ka)
        swap_kakb &= ka != kb
        s1,s2 = s12
        nocc = self.nocc
        nvir = [self.nmo[s] - nocc[s] for s in [0,1]]

        if cache_eris:
            # caching ijab and ijba
            oovv_ijab = self.get_oovv(s12, kijab)
            oovv_ijba = self.get_oovv(s12, kijba) if swap_kakb else oovv_ijab
            def get_oovv(shls_slice, kind):
                p0,p1 = shls_slice
                if kind == 'd':
                    return oovv_ijab[p0:p1]
                else:
                    return oovv_ijba[p0:p1]
        else:
            def get_oovv(shls_slice, kind):
                if kind == 'd':
                    return self.get_oovv(s12, kijab, shls_slice_i=shls_slice)
                else:
                    return self.get_oovv(s12, kijba, shls_slice_i=shls_slice)

        if blksize is None:
            mem_avail = max_memory - lib.current_memory()[0]
            fac = 2 if swap_kakb else 1
            blksize = int(np.floor(mem_avail * 0.7 /
                                   (nocc[s2]*nvir[s1]*nvir[s2]*fac * 16/1e6)))

        for p0,p1 in lib.prange(0,self.nocc[s1],blksize):
            shls_slice = (p0,p1)
            gdi = get_oovv(shls_slice, 'd')
            gxi = get_oovv(shls_slice, 'x') if swap_kakb else None
            yield gdi, gxi
            gdi = gxi = None

        if cache_eris:
            oovv_ijab = oovvijba = None

class _DFMP2ERIS_INCORE(_MP2ERIS_INCORE):

    def _common_init_(self, mp, mo_coeff=None):
        _MP2ERIS_INCORE._common_init_(self, mp, mo_coeff=mo_coeff)
        self.Lov = _init_mp_df_eris(mp, mo_coeff=self.mo_coeff)
        return self

    def get_Lov(self, s, ki, ka, shls_slice_i=None):
        if shls_slice_i is None:
            return self.Lov[s][ki,ka]
        else:
            return self.Lov[s][ki,ka][:,shls_slice_i[0]:shls_slice_i[1]]

    def get_oovv(self, s12, kijab, shls_slice_i=None):
        s1,s2 = s12
        ki,kj,ka,kb = kijab
        nkpts = len(self.kpts)
        return einsum("Lia,Ljb->iajb", self.get_Lov(s1,ki,ka,shls_slice_i),
                      self.get_Lov(s2,kj,kb)).transpose(0,2,1,3) / nkpts

def _make_eris_incore(mp, mo_coeff=None):
    eris = _MP2ERIS_INCORE()._common_init_(mp, mo_coeff=mo_coeff)
    return eris

def _make_df_eris_incore(mp, mo_coeff=None):
    eris = _DFMP2ERIS_INCORE()._common_init_(mp, mo_coeff=mo_coeff)
    return eris

def _make_df_eris_outcore(mp, mo_coeff=None):
    eris = _DFMP2ERIS_OUTCORE()._common_init_(mp, mo_coeff=mo_coeff)
    return eris

def _init_mp_df_eris(mp, mo_coeff=None, Lov=None):
    """Compute 3-center electron repulsion integrals, i.e. (L|ov) and (L|OV),
    where `L` denotes DF auxiliary basis functions and `o/O` and `v/V`
    alpha/beta-spin occupied and virtual canonical crystalline orbitals.
    Note that `o` and `v` contain kpt indices `ko` and `kv`, and the third
    kpt index `kL` is determined by the conservation of momentum.

    Arguments:
        mp (KMP2) -- A KMP2 instance
        mo_coeff (list) -- MO coeff by kpts. Generated from _add_padding if None.
        Lov (ndarray or H5 group) -- where to store integrals. If None, a numpy
            ndarray is created.

    Returns:
        Lov (list of numpy.ndarray or H5 group) -- each array/H5 group is a
            3-center DF ints for a spin, with shape
                (nkpts, nkpts, naux, nocc[spin], nvir[spin])
    """
    log = logger.new_logger(mp)

    nocc = mp.nocc
    if mo_coeff is None: mo_coeff = _add_padding_mo_coeff(mp, mp.mo_coeff)
    kpts = mp.kpts
    if Lov is None: Lov = [None] * 2
    if mp._scf.with_df._cderi is None:
        mp._scf.with_df.build()
    cderi = mp._scf.with_df._cderi

    for s in [0,1]:
        spinname = 'up' if s == 0 else 'down'
        cput0 = (logger.process_clock(), logger.perf_counter())
        Lov[s] = kmp2.ao2mo_df(cderi, mo_coeff[s], nocc[s], kpts, Lov=Lov[s])
        log.timer("transforming DF-MP2 integrals spin %s" % spinname, *cput0)

    return Lov


from pyscf.pbc import scf
scf.kuhf.KUHF.MP2 = lib.class_as_method(KUMP2)


if __name__ == '__main__':
    test_case = 2

    if test_case == 1:
        r''' Taken from kmp2.py. KUMP2 should reproduce KRMP2 when spin-symm is
        not broken (of course KUMP2 is 3x slower).
        '''
        from pyscf.pbc import gto, scf, mp

        cell = gto.Cell()
        cell.atom='''
        C 0 0 0
        '''
        cell.basis = '''
        C  S
            9.031436   -1.960629e-02
            3.821255   -1.291762e-01
            0.473725    5.822572e-01
        C  S
            0.149679    1.000000e+00
        C  P
            4.353457    8.730943e-02
            1.266307    2.797034e-01
            0.398715    5.024424e-01
        C  P
            0.124238    1.000000e+00
        '''
        cell.pseudo = 'gth-hf-rev'
        cell.a = np.eye(3) * 3
        cell.mesh = [21]*3
        cell.build()
        cell.verbose = 6

        # Running HF and MP2 with 1x1x2 Monkhorst-Pack k-point mesh
        kmf = scf.KUHF(cell, kpts=cell.make_kpts([1,1,2]), exxdiv=None)
        # kmf = scf.KUHF(cell, kpts=cell.make_kpts([1,1,2]), exxdiv=None).rs_density_fit()
        ehf = kmf.kernel()

        mymp = mp.KUMP2(kmf)
        emp2, t2 = mymp.kernel()
        print(emp2 - -0.0443318084113812)
    else:
        r''' For relatively large box size, KUMP2 should match molecular UMP2 energy
        '''
        from pyscf.pbc import gto, scf, mp
        from pyscf import scf as molscf, mp as molmp

        atom = 'O 0 0 0; O 1.2 0 0'
        a = np.eye(3) * 15
        spin = 2
        basis = 'cc-pvdz'
        pseudo = None
        cell = gto.Cell(atom=atom, a=a, basis=basis, pseudo=pseudo, spin=spin)
        cell.build()
        cell.verbose = 7

        kumf = scf.KUHF(cell, kpts=cell.make_kpts([1,1,1])).rs_density_fit()
        kumf.kernel()

        kump = mp.KUMP2(kumf)
        ekump2 = kump.kernel()[0]

        umf = molscf.UHF(cell.to_mol()).density_fit().set(verbose=3)
        umf.kernel()
        ump = molmp.UMP2(umf).set(verbose=3)
        eump2 = ump.kernel()[0]

        print('PBC KUMP2     = % .10f  % .3g' % (ekump2, ekump2 - -0.34658969808607))
        print('Mol  UMP2     = % .10f' % eump2)
        print('PBC/Mol diff  = % .10f' % (ekump2 - eump2))
