#!/usr/bin/env python
# Copyright 2014-2021 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: James McClain <jdmcclain47@gmail.com>
#         Hong-Zhou Ye <hzyechem@gmail.com>
#


'''
kpoint-adapted unrestricted MP2
t2[i,j,a,b] = <ij|ab> / D_ij^ab

t2 and eris are never stored in full, only a partial
eri of size (nkpts,nocc,nocc,nvir,nvir)
'''


import numpy as np
from scipy.linalg import block_diag
import h5py
import tempfile
import ctypes

from pyscf import lib
from pyscf.lib import logger, einsum
from pyscf.pbc.mp import kmp2
from pyscf.pbc.df import df
from pyscf.pbc.lib import kpts_helper
from pyscf.pbc.lib.kpts_helper import gamma_point
from pyscf.pbc.mp.kmp2 import _frozen_sanity_check
from pyscf.lib.parameters import LARGE_DENOM
from pyscf import __config__

libmp = lib.load_library('libmp')

WITH_T2 = getattr(__config__, 'mp_mp2_with_t2', True)


def kernel(mp, mo_energy, mo_coeff, eris=None, with_t2=WITH_T2, verbose=None):
    """Computes k-point UMP2 energy.

    Args:
        mp (KMP2): an instance of KMP2
        mo_energy (list): a nested list of numpy.ndarray. Each array contains MO
                          energies of shape (Nmo,) for one spin and kpt
        mo_coeff (list): a nested list of numpy.ndarray. Each array contains MO
                         coefficients of shape (Nao, Nmo) for one spin and kpt
        eris: generated by mp.ao2mo()
        verbose (int, optional): level of verbosity. Defaults to logger.NOTE (=3).
        with_t2 (bool, optional): whether to compute t2 amplitudes, (t2aa, t2ab, t2bb).
                                  Defaults to WITH_T2 (=True). Note that t2aa and t2bb
                                  are NOT anti-symmetrized, which is different from the
                                  molecular UMP2.

    Returns:
        KMP2 energy and t2 amplitudes (=None if with_t2 is False)
    """
    log = logger.new_logger(mp, verbose=verbose)
    if mp._kernel is None:
        if mp.with_df_ints:
            fkernel = kernel_df if with_t2 else kernel_df_C
        else:
            fkernel = kernel_fftdf
    elif callable(mp._kernel):
        fkernel = mp._kernel
    elif isinstance(mp._kernel, str):
        if mp.with_df_ints:
            fkernel = kernel_df_C if mp._kernel.lower() == 'c' else kernel_df
        else:
            fkernel = kernel_fftdf
    else:
        log.error('Unknown kernel type')
        raise ValueError

    return fkernel(mp, mo_energy, mo_coeff, eris, with_t2, verbose)

@lib.with_doc(kernel.__doc__)
def kernel_fftdf(mp, mo_energy, mo_coeff, eris=None, with_t2=WITH_T2, verbose=None):
    cput0 = (logger.process_clock(), logger.perf_counter())
    log = logger.new_logger(mp, verbose)

    if eris is None:
        eris = mp.ao2mo(mo_coeff, with_t2)

    if mo_energy is None:
        mo_energy = eris.mo_energy

    nmo = mp.nmo
    nocc = mp.nocc
    nvir = [nmo[s] - nocc[s] for s in [0,1]]
    nkpts = mp.nkpts

    kconserv = mp.khelper.kconserv

    mo_e_o = [[mo_energy[s][k][:nocc[s]] for k in range(nkpts)] for s in [0,1]]
    mo_e_v = [[mo_energy[s][k][nocc[s]:] for k in range(nkpts)] for s in [0,1]]

    # Get location of non-zero/padded elements in occupied and virtual space
    nonzero_padding = padding_k_idx(mp, kind="split")
    nonzero_opadding = [x[0] for x in nonzero_padding]
    nonzero_vpadding = [x[1] for x in nonzero_padding]

    if with_t2:
        # taa, tab, tbb
        t2 = [np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[0], nvir[0], nvir[0]), dtype=complex),
              np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[1], nvir[0], nvir[1]), dtype=complex),
              np.zeros((nkpts, nkpts, nkpts, nocc[1], nocc[1], nvir[1], nvir[1]), dtype=complex)]
    else:
        t2 = None

    def get_eia(s, ki, ka):
        eia = LARGE_DENOM * np.ones((nocc[s], nvir[s]), dtype=mo_energy[s][0].dtype)
        n0_ovp_ia = np.ix_(nonzero_opadding[s][ki], nonzero_vpadding[s][ka])
        eia[n0_ovp_ia] = (mo_e_o[s][ki][:,None] - mo_e_v[s][ka])[n0_ovp_ia]
        return eia

    # determine occ batch size
    dsize = 8 if eris.dtype == np.float64 else 16
    mem_avail = mp.max_memory - lib.current_memory()[0]
    # 4*[O]^2*V^2 = mem
    occ_blksize = min(max(nocc), max(1, int(np.floor((0.7*mem_avail*0.25*1e6/dsize /
                                                      max(nvir)**2.)**0.5))))
    log.debug('occ blksize for %s loop: %d/%s', mp.__class__.__name__, occ_blksize, nocc)

    cput1 = (logger.process_clock(), logger.perf_counter())

    tspans = np.zeros((2,2))
    tnames = ['ovov', 'energy']

    emp2_ss = emp2_os = 0.

    # same spin
    for s in [0,1]:
        s_t2 = s if s == 0 else 2

        for ki in range(nkpts):
            for kj in range(ki+1):
                fac_kikj = 1 if ki==kj else 2
                done = {(ka,kconserv[ki,ka,kj]):False for ka in range(nkpts)}
                for ka in range(nkpts):
                    kb = kconserv[ki,ka,kj]

                    if done[(ka,kb)] or done[(kb,ka)]:
                        continue

                    eia = get_eia(s,ki,ka)
                    ejb = get_eia(s,kj,kb)

                    ovov_ij = [None] * 2
                    for ibatch,(i0,i1) in enumerate(lib.prange(0,nocc[s],occ_blksize)):
                        for jbatch,(j0,j1) in enumerate(lib.prange(0,nocc[s],occ_blksize)):
                            TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                            ovov_ij[0] = eris.get_ovov((s,s), (ki,ka,kj,kb), (i0,i1), (j0,j1))
                            if ka == kb:
                                fac_swap = 1
                                ovov_ij[1] = ovov_ij[0]
                            else:
                                fac_swap = 2
                                ovov_ij[1] = eris.get_ovov((s,s), (ki,kb,kj,ka), (i0,i1), (j0,j1))
                            TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                            tspans[0] += TOCK - TICK

                            eiajb = lib.direct_sum('ia,jb->iajb', eia[i0:i1], ejb[j0:j1])

                            t2_iajb = np.conj(ovov_ij[0] / eiajb)
                            if with_t2:
                                t2[s_t2][ki,kj,ka][i0:i1,j0:j1] = t2_iajb.transpose(0,2,1,3)
                                if ki != kj:
                                    t2[s_t2][kj,ki,kb][j0:j1,i0:i1] = t2_iajb.transpose(2,0,3,1)

                            edi = einsum('iajb,iajb', t2_iajb, ovov_ij[0]).real * fac_kikj
                            exi = -einsum('iajb,ibja', t2_iajb, ovov_ij[1]).real * fac_swap * fac_kikj
                            emp2_ss += (edi + exi) * 0.5

                            t2_iajb = None

                            if ka != kb:
                                t2_ibja = np.conj(ovov_ij[1] / eiajb.transpose(0,3,2,1))
                                if with_t2:
                                    t2[s_t2][ki,kj,kb][i0:i1,j0:j1] = t2_ibja.transpose(0,2,1,3)
                                    if ki != kj:
                                        t2[s_t2][kj,ki,ka][j0:j1,i0:i1] = t2_ibja.transpose(2,0,3,1)

                                edi = einsum('iajb,iajb', t2_ibja, ovov_ij[1]).real * fac_kikj
                                emp2_ss += edi * 0.5

                                t2_ibja = None

                            eiajb = None

                            TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                            tspans[1] += TICK - TOCK

                    ovov_ij = None
                    done[(ka,kb)] = done[(kb,ka)] = True

            cput1 = log.timer_debug1(f'(sa,sb) = (%d,%d) ki = %d'%(s,s,ki), *cput1)

    # opposite spin
    sa = 0
    sb = 1
    for ki in range(nkpts):
        for kj in range(nkpts):
            for ka in range(nkpts):
                kb = kconserv[ki,ka,kj]

                eia = get_eia(sa,ki,ka)
                ejb = get_eia(sb,kj,kb)

                for ibatch,(i0,i1) in enumerate(lib.prange(0,nocc[sa],occ_blksize)):
                    for jbatch,(j0,j1) in enumerate(lib.prange(0,nocc[sb],occ_blksize)):
                        TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        ovov_ij = eris.get_ovov((sa,sb), (ki,ka,kj,kb), (i0,i1), (j0,j1))
                        TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[0] += TOCK - TICK

                        eiajb = lib.direct_sum('ia,jb->iajb', eia[i0:i1], ejb[j0:j1])

                        t2_iajb = np.conj(ovov_ij / eiajb)
                        if with_t2:
                            t2[1][ki,kj,ka][i0:i1,j0:j1] = t2_iajb.transpose(0,2,1,3)

                        edi = einsum('iajb,iajb', t2_iajb, ovov_ij).real
                        emp2_os += edi

                        t2_iajb = None
                        eiajb = None
                        ovov_ij = None

                        TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[1] += TICK - TOCK

        log.timer_debug1('(sa,sb) = (%d,%d) ki = %d' % (sa,sb,ki), *cput1)

    log.debug('')
    for tspan,tname in zip(tspans,tnames):
        log.debug(f'    CPU time for {tname:10s} {tspan[0]:9.2f} sec, wall time {tspan[1]:9.2f} sec')
    log.debug('')

    log.timer(mp.__class__.__name__, *cput0)

    emp2_ss /= nkpts
    emp2_os /= nkpts
    emp2 = lib.tag_array(emp2_ss+emp2_os, e_corr_ss=emp2_ss, e_corr_os=emp2_os)

    return emp2, t2

@lib.with_doc(kernel.__doc__)
def kernel_df(mp, mo_energy, mo_coeff, eris=None, with_t2=WITH_T2, verbose=None):
    cput0 = (logger.process_clock(), logger.perf_counter())
    log = logger.new_logger(mp, verbose)

    if eris is None:
        eris = mp.ao2mo(mo_coeff, with_t2)

    if mo_energy is None:
        mo_energy = eris.mo_energy

    nmo = mp.nmo
    nocc = mp.nocc
    nvir = [nmo[s] - nocc[s] for s in [0,1]]
    nkpts = mp.nkpts

    kconserv = mp.khelper.kconserv

    mo_e_o = [[mo_energy[s][k][:nocc[s]] for k in range(nkpts)] for s in [0,1]]
    mo_e_v = [[mo_energy[s][k][nocc[s]:] for k in range(nkpts)] for s in [0,1]]

    # Get location of non-zero/padded elements in occupied and virtual space
    nonzero_padding = padding_k_idx(mp, kind="split")
    nonzero_opadding = [x[0] for x in nonzero_padding]
    nonzero_vpadding = [x[1] for x in nonzero_padding]

    if with_t2:
        # taa, tab, tbb
        t2 = [np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[0], nvir[0], nvir[0]), dtype=complex),
              np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[1], nvir[0], nvir[1]), dtype=complex),
              np.zeros((nkpts, nkpts, nkpts, nocc[1], nocc[1], nvir[1], nvir[1]), dtype=complex)]
    else:
        t2 = None

    def get_eia(s, ki, ka):
        eia = LARGE_DENOM * np.ones((nocc[s], nvir[s]), dtype=mo_energy[s][0].dtype)
        n0_ovp_ia = np.ix_(nonzero_opadding[s][ki], nonzero_vpadding[s][ka])
        eia[n0_ovp_ia] = (mo_e_o[s][ki][:,None] - mo_e_v[s][ka])[n0_ovp_ia]
        return eia

    # determine occ batch size
    naux = mp._scf.with_df.get_naoaux()
    dsize = 8 if eris.dtype == np.float64 else 16
    mem_avail = mp.max_memory - lib.current_memory()[0]
    # 4*[O]^2*V^2 + 4*[O]XV = mem
    occ_blksize = min(max(nocc), max(1, int(np.floor(((naux**2+0.8*mem_avail*0.25*1e6/dsize)**0.5 -
                                                     naux) / (2*max(nvir))))))
    log.debug('occ blksize for %s loop: %d/%s', mp.__class__.__name__, occ_blksize, nocc)

    cput1 = (logger.process_clock(), logger.perf_counter())

    tspans = np.zeros((3,2))
    tnames = ['load', 'ovov', 'energy']

    emp2_ss = emp2_os = 0.

    # same spin
    for s in [0,1]:
        s_t2 = s if s == 0 else 2

        for ki in range(nkpts):
            for kj in range(ki+1):
                fac_kikj = 1 if ki==kj else 2
                done = {(ka,kconserv[ki,ka,kj]):False for ka in range(nkpts)}
                for ka in range(nkpts):
                    kb = kconserv[ki,ka,kj]

                    if done[(ka,kb)] or done[(kb,ka)]:
                        continue

                    eia = get_eia(s,ki,ka)
                    ejb = get_eia(s,kj,kb)

                    ovov_ij = [None] * 2
                    for ibatch,(i0,i1) in enumerate(lib.prange(0,nocc[s],occ_blksize)):
                        TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        iaL = eris.get_ovL(s, (ki,ka), (i0,i1))
                        if ka == kb:
                            ibL = iaL
                        else:
                            ibL = eris.get_ovL(s, (ki,kb), (i0,i1))
                        TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[0] += TOCK - TICK
                        for jbatch,(j0,j1) in enumerate(lib.prange(0,nocc[s],occ_blksize)):
                            TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                            if ka == kb:
                                fac_swap = 1
                                if ki == kj and ibatch == jbatch:
                                    jbL = iaL
                                else:
                                    jbL = eris.get_ovL(s, (kj,kb), (j0,j1))
                                TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                                tspans[0] += TOCK - TICK
                                ovov_ij[0] = einsum('iaL,jbL->iajb', iaL, jbL) / nkpts
                                ovov_ij[1] = ovov_ij[0]
                                TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                                tspans[1] += TICK - TOCK
                            else:
                                fac_swap = 2
                                jbL = eris.get_ovL(s, (kj,kb), (j0,j1))
                                jaL = eris.get_ovL(s, (kj,ka), (j0,j1))
                                TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                                tspans[0] += TOCK - TICK
                                ovov_ij[0] = einsum('iaL,jbL->iajb', iaL, jbL) / nkpts
                                ovov_ij[1] = einsum('iaL,jbL->iajb', ibL, jaL) / nkpts
                                TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                                tspans[1] += TICK - TOCK
                            jaL = jbL = None

                            eiajb = lib.direct_sum('ia,jb->iajb', eia[i0:i1], ejb[j0:j1])

                            t2_iajb = np.conj(ovov_ij[0] / eiajb)
                            if with_t2:
                                t2[s_t2][ki,kj,ka][i0:i1,j0:j1] = t2_iajb.transpose(0,2,1,3)
                                if ki != kj:
                                    t2[s_t2][kj,ki,kb][j0:j1,i0:i1] = t2_iajb.transpose(2,0,3,1)

                            edi = einsum('iajb,iajb', t2_iajb, ovov_ij[0]).real * fac_kikj
                            exi = -einsum('iajb,ibja', t2_iajb, ovov_ij[1]).real * fac_swap * fac_kikj
                            emp2_ss += (edi + exi) * 0.5

                            t2_iajb = None

                            if ka != kb:
                                t2_ibja = np.conj(ovov_ij[1] / eiajb.transpose(0,3,2,1))
                                if with_t2:
                                    t2[s_t2][ki,kj,kb][i0:i1,j0:j1] = t2_ibja.transpose(0,2,1,3)
                                    if ki != kj:
                                        t2[s_t2][kj,ki,ka][j0:j1,i0:i1] = t2_ibja.transpose(2,0,3,1)

                                edi = einsum('iajb,iajb', t2_ibja, ovov_ij[1]).real * fac_kikj
                                emp2_ss += edi * 0.5

                                t2_ibja = None

                            eiajb = None

                            TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                            tspans[2] += TOCK - TICK

                        iaL = ibL = None

                    ovov_ij = None
                    done[(ka,kb)] = done[(kb,ka)] = True

            cput1 = log.timer_debug1(f'(sa,sb) = (%d,%d) ki = %d'%(s,s,ki), *cput1)

    # opposite spin
    sa = 0
    sb = 1
    for ki in range(nkpts):
        for kj in range(nkpts):
            for ka in range(nkpts):
                kb = kconserv[ki,ka,kj]

                eia = get_eia(sa,ki,ka)
                ejb = get_eia(sb,kj,kb)

                for ibatch,(i0,i1) in enumerate(lib.prange(0,nocc[sa],occ_blksize)):
                    TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                    iaL = eris.get_ovL(sa, (ki,ka), (i0,i1))
                    TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                    tspans[0] += TOCK - TICK
                    for jbatch,(j0,j1) in enumerate(lib.prange(0,nocc[sb],occ_blksize)):
                        TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        jbL = eris.get_ovL(sb, (kj,kb), (j0,j1))
                        TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[0] += TOCK - TICK
                        ovov_ij = einsum('iaL,jbL->iajb', iaL, jbL) / nkpts
                        jbL = None
                        TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[1] += TICK - TOCK

                        eiajb = lib.direct_sum('ia,jb->iajb', eia[i0:i1], ejb[j0:j1])

                        t2_iajb = np.conj(ovov_ij / eiajb)
                        if with_t2:
                            t2[1][ki,kj,ka][i0:i1,j0:j1] = t2_iajb.transpose(0,2,1,3)

                        edi = einsum('iajb,iajb', t2_iajb, ovov_ij).real
                        emp2_os += edi

                        t2_iajb = None
                        eiajb = None
                        ovov_ij = None

                        TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[2] += TOCK - TICK

                    iaL = None

        log.timer_debug1('(sa,sb) = (%d,%d) ki = %d' % (sa,sb,ki), *cput1)

    log.debug('')
    for tspan,tname in zip(tspans,tnames):
        log.debug(f'    CPU time for {tname:10s} {tspan[0]:9.2f} sec, wall time {tspan[1]:9.2f} sec')
    log.debug('')

    log.timer(mp.__class__.__name__, *cput0)

    emp2_ss /= nkpts
    emp2_os /= nkpts
    emp2 = lib.tag_array(emp2_ss+emp2_os, e_corr_ss=emp2_ss, e_corr_os=emp2_os)

    return emp2, t2

@lib.with_doc(kernel.__doc__)
def kernel_df_C(mp, mo_energy, mo_coeff, eris=None, with_t2=WITH_T2, verbose=None):
    cput0 = (logger.process_clock(), logger.perf_counter())
    log = logger.new_logger(mp, verbose)

    if eris is None:
        eris = mp.ao2mo(mo_coeff, with_t2)

    if mo_energy is None:
        mo_energy = eris.mo_energy

    nmo = mp.nmo
    nocc = mp.nocc
    nvir = [nmo[s] - nocc[s] for s in [0,1]]
    nkpts = mp.nkpts

    kconserv = mp.khelper.kconserv

    mo_e_o = [[mo_energy[s][k][:nocc[s]] for k in range(nkpts)] for s in [0,1]]
    mo_e_v = [[mo_energy[s][k][nocc[s]:] for k in range(nkpts)] for s in [0,1]]

    # Get location of non-zero/padded elements in occupied and virtual space
    nonzero_padding = padding_k_idx(mp, kind="split")
    nonzero_opadding = [x[0] for x in nonzero_padding]
    nonzero_vpadding = [x[1] for x in nonzero_padding]

    if with_t2:
        log.error('DF-C kernel does not support with_t2 = True. '
                  'Run with mmp.kernel(with_t2=False) or '
                  'use DF-Python kernel by mmp._kernel = \'py\'.')
        raise NotImplementedError
        # taa, tab, tbb
        t2 = [np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[0], nvir[0], nvir[0]), dtype=complex),
              np.zeros((nkpts, nkpts, nkpts, nocc[0], nocc[1], nvir[0], nvir[1]), dtype=complex),
              np.zeros((nkpts, nkpts, nkpts, nocc[1], nocc[1], nvir[1], nvir[1]), dtype=complex)]
    else:
        t2 = None

    drv = libmp.KUMP2_contract_drv

    def get_eij(sa, sb, ki, kj):
        eij = -LARGE_DENOM * np.ones((nocc[sa], nocc[sb]), dtype=mo_energy[sa][0].dtype)
        n0_ovp_ij = np.ix_(nonzero_opadding[sa][ki], nonzero_opadding[sb][kj])
        eij[n0_ovp_ij] = (mo_e_o[sa][ki][:,None] + mo_e_o[sb][kj])[n0_ovp_ij]
        return eij
    def get_eab(sa, sb, ka, kb):
        eab = LARGE_DENOM * np.ones((nvir[sa], nvir[sb]), dtype=mo_energy[sa][0].dtype)
        n0_ovp_ab = np.ix_(nonzero_vpadding[sa][ka], nonzero_vpadding[sb][kb])
        eab[n0_ovp_ab] = (mo_e_v[sa][ka][:,None] + mo_e_v[sb][kb])[n0_ovp_ab]
        return eab

    # determine occ batch size
    naux = mp._scf.with_df.get_naoaux()
    dsize = 8 if eris.dtype == np.float64 else 16
    mem_avail = mp.max_memory - lib.current_memory()[0]
    # 4*[O]^2*V^2 + 4*[O]XV = mem
    occ_blksize = min(max(nocc), max(1, int(np.floor(((naux**2+0.8*mem_avail*0.25*1e6/dsize)**0.5 -
                                                     naux) / (2*max(nvir))))))
    log.debug('occ blksize for %s loop: %d/%s', mp.__class__.__name__, occ_blksize, nocc)

    cput1 = (logger.process_clock(), logger.perf_counter())

    tspans = np.zeros((2,2))
    tnames = ['load', 'contract']

    emp2_ss = emp2_os = 0.

    # same spin
    for s in [0,1]:
        s_t2 = s if s == 0 else 2

        for ki in range(nkpts):
            for kj in range(ki+1):
                fac_kikj = 1 if ki==kj else 2
                moeoo = get_eij(s,s,ki,kj)
                done = {(ka,kconserv[ki,ka,kj]):False for ka in range(nkpts)}
                for ka in range(nkpts):
                    kb = kconserv[ki,ka,kj]

                    if done[(ka,kb)] or done[(kb,ka)]:
                        continue

                    moevv = lib.asarray(get_eab(s,s,ka,kb).reshape(-1), order='C')

                    for ibatch,(i0,i1) in enumerate(lib.prange(0,nocc[s],occ_blksize)):
                        nocci = i1-i0
                        TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        iaLR, iaLI = eris.get_ovL(s, (ki,ka), (i0,i1), True)
                        if ka == kb:
                            ibLR, ibLI = iaLR, iaLI
                        else:
                            ibLR, ibLI = eris.get_ovL(s, (ki,kb), (i0,i1), True)
                        naux = iaLR.shape[-1]
                        for jbatch,(j0,j1) in enumerate(lib.prange(0,nocc[s],occ_blksize)):
                            noccj = j1-j0
                            if ka == kb:
                                if ki == kj and ibatch == jbatch:
                                    jbLR, jbLI = iaLR, iaLI
                                else:
                                    jbLR, jbLI = eris.get_ovL(s, (kj,kb), (j0,j1), True)
                                jaLR, jaLI = jbLR, jbLI
                            else:
                                jbLR, jbLI = eris.get_ovL(s, (kj,kb), (j0,j1), True)
                                jaLR, jaLI = eris.get_ovL(s, (kj,ka), (j0,j1), True)
                            TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                            tspans[0] += TOCK - TICK

                            ed = np.zeros(1, dtype=np.float64)
                            ex = np.zeros(1, dtype=np.float64)
                            drv(
                                ed.ctypes.data_as(ctypes.c_void_p),
                                ex.ctypes.data_as(ctypes.c_void_p),
                                iaLR.ctypes.data_as(ctypes.c_void_p),
                                iaLI.ctypes.data_as(ctypes.c_void_p),
                                ibLR.ctypes.data_as(ctypes.c_void_p),
                                ibLI.ctypes.data_as(ctypes.c_void_p),
                                jbLR.ctypes.data_as(ctypes.c_void_p),
                                jbLI.ctypes.data_as(ctypes.c_void_p),
                                jaLR.ctypes.data_as(ctypes.c_void_p),
                                jaLI.ctypes.data_as(ctypes.c_void_p),
                                ctypes.c_int(s), ctypes.c_int(s),
                                ctypes.c_int(ki), ctypes.c_int(kj),
                                ctypes.c_int(ka), ctypes.c_int(kb),
                                ctypes.c_int(i0), ctypes.c_int(j0),
                                ctypes.c_int(nocci), ctypes.c_int(noccj),
                                ctypes.c_int(nvir[s]), ctypes.c_int(nvir[s]),
                                ctypes.c_int(naux),
                                lib.asarray(moeoo[i0:i1,j0:j1],
                                            order='C').ctypes.data_as(ctypes.c_void_p),
                                moevv.ctypes.data_as(ctypes.c_void_p),
                            )
                            ed *= fac_kikj / nkpts**2
                            ex *= fac_kikj / nkpts**2

                            emp2_ss += (ed + ex) * 0.5

                            TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                            tspans[1] += TICK - TOCK

                            jaLR = jaLI = jbLR = jbLI = None

                        iaLR = iaLI = ibLR = ibLI = None

                    done[(ka,kb)] = done[(kb,ka)] = True

            cput1 = log.timer_debug1(f'(sa,sb) = (%d,%d) ki = %d'%(s,s,ki), *cput1)

    # opposite spin
    sa = 0
    sb = 1
    ibLR = ibLI = jaLR = jaLI = lib.c_null_ptr()
    for ki in range(nkpts):
        for kj in range(nkpts):
            moeoo = get_eij(sa,sb,ki,kj)
            for ka in range(nkpts):
                kb = kconserv[ki,ka,kj]

                moevv = lib.asarray(get_eab(sa,sb,ka,kb).reshape(-1), order='C')

                for ibatch,(i0,i1) in enumerate(lib.prange(0,nocc[sa],occ_blksize)):
                    nocci = i1-i0
                    TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                    iaLR, iaLI = eris.get_ovL(sa, (ki,ka), (i0,i1), True)
                    TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                    tspans[0] += TOCK - TICK
                    for jbatch,(j0,j1) in enumerate(lib.prange(0,nocc[sb],occ_blksize)):
                        noccj = j1-j0
                        TICK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        jbLR, jbLI = eris.get_ovL(sb, (kj,kb), (j0,j1), True)
                        TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[0] += TOCK - TICK

                        ed = np.zeros(1, dtype=np.float64)
                        ex = np.zeros(1, dtype=np.float64)
                        drv(
                            ed.ctypes.data_as(ctypes.c_void_p),
                            ex.ctypes.data_as(ctypes.c_void_p),
                            iaLR.ctypes.data_as(ctypes.c_void_p),
                            iaLI.ctypes.data_as(ctypes.c_void_p),
                            ibLR, ibLI,
                            jbLR.ctypes.data_as(ctypes.c_void_p),
                            jbLI.ctypes.data_as(ctypes.c_void_p),
                            jaLR, jaLI,
                            ctypes.c_int(sa), ctypes.c_int(sb),
                            ctypes.c_int(ki), ctypes.c_int(kj),
                            ctypes.c_int(ka), ctypes.c_int(kb),
                            ctypes.c_int(i0), ctypes.c_int(j0),
                            ctypes.c_int(nocci), ctypes.c_int(noccj),
                            ctypes.c_int(nvir[sa]), ctypes.c_int(nvir[sb]),
                            ctypes.c_int(naux),
                            lib.asarray(moeoo[i0:i1,j0:j1],
                                        order='C').ctypes.data_as(ctypes.c_void_p),
                            moevv.ctypes.data_as(ctypes.c_void_p),
                        )
                        ed *= fac_kikj / nkpts**2

                        emp2_os += ed

                        jbLR = jbLI = None

                        TOCK = np.asarray((logger.process_clock(), logger.perf_counter()))
                        tspans[1] += TOCK - TICK

                    iaLR = iaLI = None

        log.timer_debug1('(sa,sb) = (%d,%d) ki = %d' % (sa,sb,ki), *cput1)

    log.debug('')
    for tspan,tname in zip(tspans,tnames):
        log.debug(f'    CPU time for {tname:10s} {tspan[0]:9.2f} sec, wall time {tspan[1]:9.2f} sec')
    log.debug('')

    log.timer(mp.__class__.__name__, *cput0)

    emp2_ss /= nkpts
    emp2_os /= nkpts
    emp2 = lib.tag_array(emp2_ss+emp2_os, e_corr_ss=emp2_ss, e_corr_os=emp2_os)

    return emp2, t2


def _iterative_kernel(self, eris):
    raise NotImplementedError


def padding_k_idx(mp, kind="split"):
    """For a description, see `padding_k_idx` in kmp2.py.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        kind (str): either "split" (occupied and virtual spaces are split) or "joint"
        (occupied and virtual spaces are the joint;

    Returns:
        Two lists corresponding to the occupied and virtual spaces for kind="split".
        Each list contains integer arrays with indexes pointing to actual non-zero
        entries in the padded vector/matrix/tensor. If kind="joint", a single list of
        arrays is returned corresponding to the entire MO space.
    """
    if kind not in ("split", "joint"):
        raise ValueError("The 'kind' argument must be one of 'split', 'joint'")

    if kind == "split":
        indexes_oa = []
        indexes_va = []
        indexes_ob = []
        indexes_vb = []
    else:
        indexesa = []
        indexesb = []

    dense_oa, dense_ob = mp.nocc
    dense_nmoa, dense_nmob = mp.nmo
    dense_va = dense_nmoa - dense_oa
    dense_vb = dense_nmob - dense_ob

    nocca_per_kpt, noccb_per_kpt = np.asarray(get_nocc(mp, per_kpoint=True))
    nmoa_per_kpt, nmob_per_kpt = np.asarray(get_nmo(mp, per_kpoint=True))

    # alpha spin
    for k_oa, k_nmoa in zip(nocca_per_kpt, nmoa_per_kpt):
        k_va = k_nmoa - k_oa
        if kind == "split":
            indexes_oa.append(np.arange(k_oa))
            indexes_va.append(np.arange(dense_va - k_va, dense_va))
        else:
            indexesa.append(np.concatenate((
                np.arange(k_oa),
                np.arange(dense_nmoa - k_va, dense_nmoa),
            )))

    # beta spin
    for k_ob, k_nmob in zip(noccb_per_kpt, nmob_per_kpt):
        k_vb = k_nmob - k_ob
        if kind == "split":
            indexes_ob.append(np.arange(k_ob))
            indexes_vb.append(np.arange(dense_vb - k_vb, dense_vb))
        else:
            indexesb.append(np.concatenate((
                np.arange(k_ob),
                np.arange(dense_nmob - k_vb, dense_nmob),
            )))

    if kind == "split":
        return [indexes_oa, indexes_va], [indexes_ob, indexes_vb]
    else:
        return indexesa, indexesb


def padded_mo_energy(mp, mo_energy):
    """
    Pads energies of active MOs.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        mo_energy (ndarray): original non-padded molecular energies;

    Returns:
        Padded molecular energies.
    """
    frozen_mask = get_frozen_mask(mp)
    padding_convention = padding_k_idx(mp, kind="joint")
    nkpts = mp.nkpts

    result = (np.zeros((nkpts, mp.nmo[0]), dtype=mo_energy[0][0].dtype),
              np.zeros((nkpts, mp.nmo[1]), dtype=mo_energy[1][0].dtype))
    for spin in [0, 1]:
        for k in range(nkpts):
            result[spin][np.ix_([k], padding_convention[spin][k])] = \
                                    mo_energy[spin][k][frozen_mask[spin][k]]

    return result


def padded_mo_coeff(mp, mo_coeff):
    """
    Pads coefficients of active MOs.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        mo_coeff (ndarray): original non-padded molecular coefficients;

    Returns:
        Padded molecular coefficients.
    """
    frozen_mask = get_frozen_mask(mp)
    padding_convention = padding_k_idx(mp, kind="joint")
    nkpts = mp.nkpts

    result = (np.zeros((nkpts, mo_coeff[0][0].shape[0], mp.nmo[0]),
                       dtype=mo_coeff[0][0].dtype),
              np.zeros((nkpts, mo_coeff[1][0].shape[0], mp.nmo[1]),
                       dtype=mo_coeff[1][0].dtype))
    for spin in [0, 1]:
        for k in range(nkpts):
            result[spin][np.ix_([k], np.arange(result[spin].shape[1]),
                         padding_convention[spin][k])] = \
                                    mo_coeff[spin][k][:,frozen_mask[spin][k]]

    return result


def _is_arraylike(x):
    return isinstance(x, (tuple, list, np.ndarray))


def get_nocc(mp, per_kpoint=False):
    '''Number of occupied orbitals for k-point calculations.

    Number of occupied orbitals for use in a calculation with k-points, taking into
    account frozen orbitals.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        per_kpoint (bool, optional): True returns the number of occupied
            orbitals at each k-point.  False gives the max of this list.

    Returns:
        nocc (int, list of int): Number of occupied orbitals. For return type, see description of arg
            `per_kpoint`.

    Notes:
        For specifying frozen orbitals inside mp, the following options are accepted:

            +=========================+========================================+===============================+
            | Argument (Example)      | Argument Meaning                       | Example Meaning               |
            +=========================+========================================+===============================+
            | int (1)                 | Freeze the same number of orbitals     | Freeze one (lowest) orbital   |
            |                         | regardless of spin and/or kpt          | for all kpts and spin cases   |
            +-------------------------+----------------------------------------+-------------------------------+
            | 2-tuple of list of int  | inner list: List of orbitals indices   | Freeze the orbitals [0,4] for |
            | ([0, 4], [0, 5, 6])     |   to freeze at all kpts                | spin0, and orbitals [0,5,6]   |
            |                         | outer list: Spin index                 | for spin1 at all kpts         |
            +-------------------------+----------------------------------------+-------------------------------+
            | list(2) of list of list | inner list: list of orbital indices to | Freeze orbital 0 for spin0 at |
            | ([[0,],[]],             |   freeze at each kpt for given spin    | kpt0, and freeze orbital 0,1  |
            |  [[0,1],[4]])           | outer list: spin index                 | for spin1 at kpt0 and orbital |
            |                         |                                        | 4 at kpt1                     |
            +-------------------------+----------------------------------------+-------------------------------+

    '''
    for spin in [0,1]:
        for i, moocc in enumerate(mp.mo_occ[spin]):
            if np.any(moocc % 1 != 0):
                raise RuntimeError(
                    "Fractional occupation numbers encountered @ kp={:d}: {}.  "
                    "This may have been caused by smearing of occupation numbers "
                    "in the mean-field calculation. If so, consider executing "
                    "mf.smearing_method = False; mf.mo_occ = mf.get_occ() prior "
                    "to calling this".format(i, moocc))
    if mp._nocc is not None:
        return mp._nocc

    elif mp.frozen is None:
        nocc = [[np.count_nonzero(mp.mo_occ[0][k] > 0) for k in range(mp.nkpts)],
                [np.count_nonzero(mp.mo_occ[1][k] > 0) for k in range(mp.nkpts)]]

    elif isinstance(mp.frozen, (int, np.integer)):
        nocc = [0]*2
        for spin in [0,1]:
            nocc[spin] = [(np.count_nonzero(mp.mo_occ[spin][k] > 0) - mp.frozen) for k in range(mp.nkpts)]

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (int, np.integer))):  # case example: ([0, 4], [0, 5, 6])
        nocc = [0]*2
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            nocc_spin = []
            for ikpt in range(mp.nkpts):
                max_occ_idx = np.max(np.where(mp.mo_occ[spin][ikpt] > 0))
                frozen_nocc = np.sum(np.array(mp.frozen[spin]) <= max_occ_idx)
                nocc_spin.append(np.count_nonzero(mp.mo_occ[spin][ikpt]) - frozen_nocc)
            nocc[spin] = nocc_spin

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (list, np.ndarray))):  # case example: ([[0,],[]], [[0,1],[4]])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            nkpts = len(mp.frozen[spin])
            if nkpts != mp.nkpts:
                raise RuntimeError('Frozen list has a different number of k-points (length) than passed in'
                                   'mean-field/correlated calculation.  \n\nCalculation nkpts = %d, frozen'
                                   'list = %s (length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        nocc = [0]*2
        for spin in [0,1]:
            [_frozen_sanity_check(frozen, mo_occ, ikpt)
             for ikpt, frozen, mo_occ in zip(range(nkpts), mp.frozen[spin], mp.mo_occ[spin])]
            nocc_spin = []
            for ikpt, frozen in enumerate(mp.frozen[spin]):
                max_occ_idx = np.max(np.where(mp.mo_occ[spin][ikpt] > 0))
                frozen_nocc = np.sum(np.array(frozen) <= max_occ_idx)
                nocc_spin.append(np.count_nonzero(mp.mo_occ[spin][ikpt]) - frozen_nocc)
            nocc[spin] = nocc_spin
    else:
        raise NotImplementedError('No known conversion for frozen %s' % mp.frozen)

    for spin in [0,1]:
        assert any(np.array(nocc[spin]) > 0), (
            'Must have occupied orbitals (spin=%d)! \n\nnocc %s\nfrozen %s\nmo_occ %s' %
            (spin, nocc, mp.frozen, mp.mo_occ))

    nocca, noccb = nocc
    if not per_kpoint:
        nocca = np.amax(nocca)
        noccb = np.amax(noccb)

    return nocca, noccb


def get_nmo(mp, per_kpoint=False):
    '''Number of orbitals for k-point calculations.

    Number of orbitals for use in a calculation with k-points, taking into account
    frozen orbitals.

    Note:
        If `per_kpoint` is False, then the number of orbitals here is equal to max(nocc) + max(nvir),
        where each max is done over all k-points.  Otherwise the number of orbitals is returned
        as a list of number of orbitals at each k-point.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        per_kpoint (bool, optional): True returns the number of orbitals at each k-point.
            For a description of False, see Note.

    Returns:
        nmo (int, list of int): Number of orbitals. For return type, see description of arg
            `per_kpoint`.

    '''
    if mp._nmo is not None:
        return mp._nmo

    nmo = [0, 0]
    if isinstance(mp.frozen, (int, np.integer)):
        for spin in [0,1]:
            nmo[spin] = [len(mp.mo_occ[spin][k]) - mp.frozen for k in range(mp.nkpts)]

    elif mp.frozen is None:
        nmo = [[len(mp.mo_occ[0][k]) for k in range(mp.nkpts)],
               [len(mp.mo_occ[1][k]) for k in range(mp.nkpts)]]

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (int, np.integer))):  # case example: ([0, 4], [0, 5, 6])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            nmo[spin] = [len(mp.mo_occ[spin][ikpt]) - len(mp.frozen[spin]) for ikpt in range(mp.nkpts)]

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (list, np.ndarray))):  # case example: ([[0,],[]], [[0,1],[4]])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            nkpts = len(mp.frozen[spin])
            if nkpts != mp.nkpts:
                raise RuntimeError('Frozen list has a different number of k-points (length) than passed in'
                                   'mean-field/correlated calculation.  \n\nCalculation nkpts = %d, frozen'
                                   'list = %s (length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin][ikpt], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            nmo[spin] = [len(mp.mo_occ[spin][ikpt]) - len(mp.frozen[spin][ikpt]) for ikpt in range(nkpts)]

    else:
        raise NotImplementedError('No known conversion for frozen %s' % mp.frozen)

    for spin in [0,1]:
        assert all(np.array(nmo[spin]) > 0), (
            'Must have a positive number of orbitals! (spin=%d)'
            '\n\nnmo %s\nfrozen %s\nmo_occ %s' % (spin, nmo, mp.frozen, mp.mo_occ))

    nmoa, nmob = nmo
    if not per_kpoint:
        # Depending on whether there are more occupied bands, we want to make sure    that
        # nmo has enough room for max(nocc) + max(nvir) number of orbitals for        occupied
        # and virtual space
        nocca, noccb = mp.get_nocc(per_kpoint=True)
        nmoa = np.amax(nocca) + np.max(np.array(nmoa) - np.array(nocca))
        nmob = np.amax(noccb) + np.max(np.array(nmob) - np.array(noccb))

    return nmoa, nmob


def get_frozen_mask(mp):
    '''Boolean mask for orbitals in k-point post-HF method.

    Creates a boolean mask to remove frozen orbitals and keep other orbitals for post-HF
    calculations.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.

    Returns:
        moidx (list of :obj:`ndarray` of `np.bool`): Boolean mask of orbitals to include.

    '''
    moidx = [[np.ones(x.size, dtype=np.bool_) for x in mp.mo_occ[s]] for s in [0,1]]

    if mp.frozen is None:
        pass

    elif isinstance(mp.frozen, (int, np.integer)):
        for spin in [0,1]:
            for idx in moidx[spin]:
                idx[:mp.frozen] = False

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (int, np.integer))):  # case example: ([0, 4], [0, 5, 6])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            for ikpt, kpt_occ in enumerate(moidx[spin]):
                kpt_occ[mp.frozen[spin]] = False

    elif (_is_arraylike(mp.frozen[0]) and
          isinstance(mp.frozen[0][0], (list, np.ndarray))):  # case example: ([[0,],[]], [[0,1],[4]])
        assert(len(mp.frozen) == 2)
        for spin in [0,1]:
            nkpts = len(mp.frozen[spin])
            if nkpts != mp.nkpts:
                raise RuntimeError('Frozen list has a different number of k-points (length) than passed in'
                                   'mean-field/correlated calculation.  \n\nCalculation nkpts = %d, frozen'
                                   'list = %s (length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        for spin in [0,1]:
            [_frozen_sanity_check(mp.frozen[spin][ikpt], mp.mo_occ[spin][ikpt], ikpt) for ikpt in range(mp.nkpts)]
            for ikpt, kpt_occ in enumerate(moidx[spin]):
                kpt_occ[mp.frozen[spin][ikpt]] = False
    else:
        raise NotImplementedError('No known conversion for frozen %s' % mp.frozen)

    return moidx


def _add_padding(mp, mo_coeff, mo_energy):
    mo_coeff = _add_padding_mo_coeff(mp, mo_coeff)
    mo_energy = _add_padding_mo_energy(mp, mo_energy)
    return mo_coeff, mo_energy

def _add_padding_mo_coeff(mp, mo_coeff):
    nmo = mp.nmo
    if not (np.all([x.shape[1] == nmo[0] for x in mo_coeff[0]]) and
            np.all([x.shape[1] == nmo[1] for x in mo_coeff[1]])):
        mo_coeff = padded_mo_coeff(mp, mo_coeff)
    return mo_coeff

def _add_padding_mo_energy(mp, mo_energy):
    nmo = mp.nmo
    if not (np.all([x.shape[0] == nmo[0] for x in mo_energy[0]]) and
            np.all([x.shape[0] == nmo[1] for x in mo_energy[1]])):
        mo_energy = padded_mo_energy(mp, mo_energy)
    return mo_energy


def make_rdm1(mp, t2=None, kind="compact"):
    r"""
    One-particle spin density matrices dm1a, dm1b in MO basis (the occupied-virtual
    blocks due to the orbital response contribution are not included).

    dm1a[p,q] = <q_alpha^\dagger p_alpha>
    dm1b[p,q] = <q_beta^\dagger p_beta>

    dm1[p,q] = <q_alpha^\dagger p_alpha> + <q_beta^\dagger p_beta>

    The convention of 1-pdm is based on McWeeney's book, Eq (5.4.20).
    The contraction between 1-particle Hamiltonian and rdm1 is
    E = sum([einsum('pq,qp', h1, rdm1[s]) for s in [0,1]])

    Args:
        mp (KUMP2): a KUMP2 kernel object;
        t2 (ndarray): a t2 MP2 tensor;
        kind (str): either 'compact' or 'padded' - defines behavior for k-dependent MO basis sizes;

    Returns:
        A k-dependent single-particle density matrix.
    """
    if kind not in ("compact", "padded"):
        raise ValueError("The 'kind' argument should be either 'compact' or 'padded'")
    d_imds = _gamma1_intermediates(mp, t2=t2)
    result = []
    padding_idxs = padding_k_idx(mp, kind="joint")
    for s in [0,1]:
        res = []
        for (oo, vv), idxs in zip(zip(*d_imds[s]), padding_idxs[s]):
            oo += np.eye(*oo.shape) * 0.5
            d = block_diag(oo, vv)
            d += d.conj().T
            if kind == "padded":
                res.append(d)
            else:
                res.append(d[np.ix_(idxs, idxs)])
        result.append(res)
    return result

def make_rdm2(mp, t2=None, kind="compact"):
    r'''
    Two-particle spin density matrices dm2aa, dm2ab, dm2bb in MO basis

    .. math::

        dm2aa[p,q,r,s] = <p_\alpha^\dagger r_\alpha^\dagger s_\alpha q_\alpha>
        dm2ab[p,q,r,s] = <p_\alpha^\dagger r_\beta^\dagger  s_\beta  q_\alpha>
        dm2bb[p,q,r,s] = <p_\beta^\dagger  r_\beta^\dagger  s_\beta  q_\beta>

    (p,q correspond to one particle and r,s correspond to another particle)
    Two-particle density matrix should be contracted to integrals with the
    pattern below to compute energy

    E = numpy.einsum('pqrs,pqrs', eri_aa, dm2_aa)
    E+= numpy.einsum('pqrs,pqrs', eri_ab, dm2_ab)
    E+= numpy.einsum('pqrs,rspq', eri_ba, dm2_ab)
    E+= numpy.einsum('pqrs,pqrs', eri_bb, dm2_bb)

    where eri_aa[p,q,r,s] = (p_alpha q_alpha | r_alpha s_alpha )
    eri_ab[p,q,r,s] = ( p_alpha q_alpha | r_beta s_beta )
    eri_ba[p,q,r,s] = ( p_beta q_beta | r_alpha s_alpha )
    eri_bb[p,q,r,s] = ( p_beta q_beta | r_beta s_beta )
    '''
    if kind not in ("compact", "padded"):
        raise ValueError("The 'kind' argument should be either 'compact' or 'padded'")
    if t2 is None: t2 = mp.t2
    dm1 = mp.make_rdm1(t2, "padded")
    nmo = mp.nmo
    nocc = mp.nocc
    nkpts = mp.nkpts
    dtype = t2[0].dtype

    t2aa, t2ab, t2bb = t2

    dm2 = [np.zeros((nkpts,nkpts,nkpts,nmo[0],nmo[0],nmo[0],nmo[0]),dtype=dtype),
           np.zeros((nkpts,nkpts,nkpts,nmo[0],nmo[0],nmo[1],nmo[1]),dtype=dtype),
           np.zeros((nkpts,nkpts,nkpts,nmo[1],nmo[1],nmo[1],nmo[1]),dtype=dtype)]
    dm2aa, dm2ab, dm2bb = dm2

    for ki in range(nkpts):
        for kj in range(nkpts):
            for ka in range(nkpts):
                kb = mp.khelper.kconserv[ki, ka, kj]

                dovov = t2aa[ki, kj, ka].transpose(0,2,1,3) - t2aa[kj, ki, ka].transpose(1,2,0,3)
                nocc1 = nocc2 = nocc[0]
                dm2aa[ki,ka,kj,:nocc1,nocc1:,:nocc2,nocc2:] = dovov
                dm2aa[ka,ki,kb,nocc1:,:nocc1,nocc2:,:nocc2] = dovov.transpose(1,0,3,2).conj()

                dovov = t2bb[ki, kj, ka].transpose(0,2,1,3) - t2bb[kj, ki, ka].transpose(1,2,0,3)
                nocc1 = nocc2 = nocc[1]
                dm2bb[ki,ka,kj,:nocc1,nocc1:,:nocc2,nocc2:] = dovov
                dm2bb[ka,ki,kb,nocc1:,:nocc1,nocc2:,:nocc2] = dovov.transpose(1,0,3,2).conj()

                dovov = t2ab[ki, kj, ka].transpose(0,2,1,3)
                nocc1, nocc2 = nocc
                dm2ab[ki,ka,kj,:nocc1,nocc1:,:nocc2,nocc2:] = dovov
                dm2ab[ka,ki,kb,nocc1:,:nocc1,nocc2:,:nocc2] = dovov.transpose(1,0,3,2).conj()

    nonzero_padding = padding_k_idx(mp, kind="split")
    occidx = [x[0] for x in nonzero_padding]
    for s in [0,1]:
        for ki in range(nkpts):
            for i in occidx[s][ki]:
                dm1[s][ki][i,i] -= 1

    for ki in range(nkpts):
        for kp in range(nkpts):
            for i in occidx[0][ki]:
                dm2aa[ki,ki,kp,i,i,:,:] += dm1[0][kp].T
                dm2aa[kp,kp,ki,:,:,i,i] += dm1[0][kp].T
                dm2aa[kp,ki,ki,:,i,i,:] -= dm1[0][kp].T
                dm2aa[ki,kp,kp,i,:,:,i] -= dm1[0][kp]

                dm2ab[ki,ki,kp,i,i,:,:] += dm1[1][kp].T

            for i in occidx[1][ki]:
                dm2bb[ki,ki,kp,i,i,:,:] += dm1[1][kp].T
                dm2bb[kp,kp,ki,:,:,i,i] += dm1[1][kp].T
                dm2bb[kp,ki,ki,:,i,i,:] -= dm1[1][kp].T
                dm2bb[ki,kp,kp,i,:,:,i] -= dm1[1][kp]

                dm2ab[kp,kp,ki,:,:,i,i] += dm1[0][kp].T

    for ki in range(nkpts):
        for kj in range(nkpts):
            for i in occidx[0][ki]:
                for j in occidx[0][kj]:
                    dm2aa[ki,ki,kj,i,i,j,j] += 1
                    dm2aa[ki,kj,kj,i,j,j,i] -= 1

            for i in occidx[1][ki]:
                for j in occidx[1][kj]:
                    dm2bb[ki,ki,kj,i,i,j,j] += 1
                    dm2bb[ki,kj,kj,i,j,j,i] -= 1

            for i in occidx[0][ki]:
                for j in occidx[1][kj]:
                    dm2ab[ki,ki,kj,i,i,j,j] += 1

    if kind == "padded":
        return dm2
    else:
        idx = padding_k_idx(mp, kind="joint")
        result = []

        for spin in ['aa','ab','bb']:
            res = np.ndarray((nkpts,nkpts,nkpts), dtype=object)
            for kp in range(nkpts):
                for kq in range(nkpts):
                    for kr in range(nkpts):
                        ks = mp.khelper.kconserv[kp, kq, kr]
                        if spin == 'aa':
                            res[kp,kq,kr] = dm2aa[kp,kq,kr][np.ix_(idx[0][kp],idx[0][kq],
                                                                   idx[0][kr],idx[0][ks])]
                        elif spin == 'bb':
                            res[kp,kq,kr] = dm2bb[kp,kq,kr][np.ix_(idx[1][kp],idx[1][kq],
                                                                   idx[1][kr],idx[1][ks])]
                        else:
                            res[kp,kq,kr] = dm2ab[kp,kq,kr][np.ix_(idx[0][kp],idx[0][kq],
                                                                   idx[1][kr],idx[1][ks])]
            result.append(res)

        return result

def _gamma1_intermediates(mp, t2=None):
    # Memory optimization should be here
    if t2 is None:
        t2 = mp.t2
    if t2 is None:
        raise NotImplementedError("Run kmp2.kernel with `with_t2=True`")
    nmo = mp.nmo
    nocc = mp.nocc
    nvir = [nmo[s] - nocc[s] for s in [0,1]]
    nkpts = mp.nkpts
    dtype = np.result_type(*t2)

    dm1occ = [np.zeros((nkpts, nocc[s], nocc[s]), dtype=dtype) for s in [0,1]]
    dm1vir = [np.zeros((nkpts, nvir[s], nvir[s]), dtype=dtype) for s in [0,1]]

    for s in [0,1]:
        s_t2 = s if s == 0 else 2
        for ki in range(nkpts):
            for kj in range(nkpts):
                for ka in range(nkpts):
                    kb = mp.khelper.kconserv[ki, ka, kj]

                    dm1vir[s][kb] += (
                        einsum('ijax,ijay->yx', t2[s_t2][ki][kj][ka].conj(), t2[s_t2][ki][kj][ka]) -
                        einsum('ijax,ijya->yx', t2[s_t2][ki][kj][ka].conj(), t2[s_t2][ki][kj][kb])
                    )
                    if s == 0:
                        dm1vir[s][kb] += einsum('jixa,jiya->yx', t2[1][kj][ki][kb].conj(),
                                                t2[1][kj][ki][kb])
                    else:
                        dm1vir[s][kb] += einsum('ijax,ijay->yx', t2[1][ki][kj][ka].conj(),
                                                t2[1][ki][kj][ka])

                    dm1occ[s][kj] += (
                        einsum('ixab,iyab->xy', t2[s_t2][ki][kj][ka].conj(), t2[s_t2][ki][kj][ka]) -
                        einsum('ixab,iyba->xy', t2[s_t2][ki][kj][ka].conj(), t2[s_t2][ki][kj][kb])
                    )
                    if s == 0:
                        dm1occ[s][kj] += einsum('xiba,yiba->xy', t2[1][kj][ki][kb].conj(),
                                                t2[1][kj][ki][kb])
                    else:
                        dm1occ[s][kj] += einsum('ixab,iyab->xy', t2[1][ki][kj][ka].conj(),
                                                t2[1][ki][kj][ka])

    for s in [0,1]:
        dm1occ[s] *= 0.5
        dm1vir[s] *= 0.5

    return ((-dm1occ[0], dm1vir[0]), (-dm1occ[1], dm1vir[1]))


class KUMP2(kmp2.KMP2):
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2

    def kernel(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=WITH_T2):
        '''
        Args:
            with_t2 : bool
                Whether to generate and hold t2 amplitudes in memory.
        '''
        if self.verbose >= logger.WARN:
            self.check_sanity()

        self.dump_flags()

        self.e_hf = self.get_e_hf(mo_coeff=mo_coeff)

        if eris is None:
            eris = self.ao2mo(mo_coeff, with_t2)

        if self._scf.converged:
            self.e_corr, self.t2 = self.init_amps(mo_energy, mo_coeff, eris, with_t2)
        else:
            self.converged, self.e_corr, self.t2 = _iterative_kernel(self, eris)

        self.e_corr_ss = getattr(self.e_corr, 'e_corr_ss', 0)
        self.e_corr_os = getattr(self.e_corr, 'e_corr_os', 0)
        self.e_corr = float(self.e_corr)

        self._finalize()

        return self.e_corr, self.t2

    def ao2mo(self, mo_coeff=None, with_t2=WITH_T2):
        return _make_df_eris(self, mo_coeff, with_t2, verbose=self.verbose)

    # For non-canonical MP2
    # energy = energy
    # update_amps = update_amps
    def init_amps(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=WITH_T2):
        return kernel(self, mo_energy, mo_coeff, eris, with_t2)

def _mem_usage(nocc, nvir, nkpts, naux, dsize, with_t2=WITH_T2):
    '''
        basic   = t2 + 4*ovov
        incore  = kLov + basic
        outcore = basic
    '''
    nocc = max(nocc)
    nvir = max(nvir)
    # 4 ovov for ovov(ka,kb), ovov(kb,ka), t2, eiajb
    basic = (nocc*nvir)**2*4
    if with_t2:
        basic += 3*nkpts**3*(nocc*nvir)**2
    basic *= dsize/1e6
    incore = 2*nkpts**2*naux*nocc*nvir * dsize/1e6 + basic
    outcore = basic
    return incore, outcore, basic

class _ChemistsERIs:
    def __init__(self, mol=None):
        self.mol = mol
        self.mo_coeff = None
        self.nocc = None
        self.fock = None
        self.dtype = None

        # for GDF
        self._ovL = None
        self._ovL_to_save = None
        self.ovL = None

        # for FFTDF
        self._get_ovov = None

    def _common_init_(self, mp, mo_coeff=None):
        if mo_coeff is None:
            mo_coeff = mp.mo_coeff
        if mo_coeff is None:
            raise RuntimeError('mo_coeff, mo_energy are not initialized.\n'
                               'You may need to call mf.kernel() to generate them.')

        self.mo_coeff = padded_mo_coeff(mp, mo_coeff)
        self.mol = mp.mol

        if gamma_point(mp._scf.kpts):
            self.dtype = np.float64
        else:
            self.dtype = np.complex128

        if mo_coeff is mp._scf.mo_coeff and mp._scf.converged:
            # The canonical MP2 from a converged SCF result. Rebuilding fock can be skipped
            self.mo_energy = padded_mo_energy(mp, mp._scf.mo_energy)
            self.fock = [[np.diag(moe) for moe in kmoe] for kmoe in self.mo_energy]
        else:
            dm = mp._scf.make_rdm1(mo_coeff, mp.mo_occ)
            vhf = mp._scf.get_veff(mp.mol, dm)
            fockao = mp._scf.get_fock(vhf=vhf, dm=dm)
            self.fock = [[C.conj().T.dot(f).dot(C) for f,C in zip(kf,kC)]
                         for kf,kC in zip(fockao,mo_coeff)]
            mo_energy = [[f.diagonal().real for f in kf] for kf in self.fock]

            self.mo_energy = padded_mo_energy(mp, mo_energy)
        return self

    def get_ovov(self, sab, kiajb, i01, j01):
        return self._get_ovov(sab, kiajb, i01, j01)

    def get_ovL(self, s, kia, i01, RIsep=False):
        ki,ka = kia
        i0,i1 = i01
        if isinstance(self.ovL, np.ndarray):
            ovL = self.ovL[s]
            if RIsep:
                return (np.asarray(ovL[ki,ka][i0:i1].real, order='C'),
                        np.asarray(ovL[ki,ka][i0:i1].imag, order='C'))
            else:
                return np.asarray(ovL[ki,ka][i0:i1])
        else:
            ovL = self.ovL[f'{s}']
            if RIsep:
                return (np.asarray(ovL[f'{ki},{ka}'][i0:i1].real, order='C'),
                        np.asarray(ovL[f'{ki},{ka}'][i0:i1].imag, order='C'))
            else:
                return np.asarray(ovL[f'{ki},{ka}'][i0:i1])

def _make_df_eris(mymp, mo_coeff=None, with_t2=WITH_T2, verbose=None):
    log = logger.new_logger(mymp, verbose)
    time0 = (logger.process_clock(), logger.perf_counter())
    eris = _ChemistsERIs()
    eris._common_init_(mymp, mo_coeff)
    mo_coeff = eris.mo_coeff
    mf = mymp._scf
    kpts = mf.kpts

    if gamma_point(kpts):
        dtype = np.float64
        dsize = 8
    else:
        dtype = np.complex128
        dsize = 16

    # determine incore/outcore
    nocc = mymp.nocc
    nmo = mymp.nmo
    nvir = [nmo[s] - nocc[s] for s in [0,1]]
    nkpts = len(kpts)

    with_df_ints = mymp.with_df_ints and isinstance(mymp._scf.with_df, df.GDF)

    if with_df_ints:
        naux = mymp._scf.with_df.get_naoaux()
        mem_incore, mem_outcore, mem_basic = _mem_usage(nocc, nvir, nkpts, naux, dsize, with_t2)
        mem_now = lib.current_memory()[0]
        max_memory = max(0, mymp.max_memory - mem_now)
        if max_memory < mem_basic:
            log.warn('Not enough memory for integral transformation. '
                     'Available mem %s MB, required mem %s MB',
                     max_memory, mem_basic)

        if eris._ovL is not None:
            if isinstance(eris._ovL, np.ndarray):
                eris.ovL = eris._ovL
                log.debug('Incore 3c integrals are found')
            else:
                eris.ovL = h5py.File(eris._ovL, 'r')
                log.debug('Outcore 3c integrals are found %s', eris._ovL)
        else:
            if mymp.mol.incore_anyway or mem_incore < max_memory:
                s_ovL = eris.ovL = np.ndarray((2,nkpts,nkpts), dtype=object)
                log.debug('Transformed 3c integrals will be saved in memory')
            else:
                if eris._ovL_to_save is None:
                    eris._ovL_to_save = tempfile.NamedTemporaryFile(dir=lib.param.TMPDIR)
                if isinstance(eris._ovL_to_save, str):
                    eris.ovL = h5py.File(eris._ovL_to_save, 'w')
                    log.debug('Transformed 3c integrals will be saved in %s', eris._ovL_to_save)
                else:
                    eris.ovL = h5py.File(eris._ovL_to_save.name, 'w')
                    log.debug('Transformed 3c integrals will be saved in %s', eris._ovL_to_save.name)
                s_ovL = [eris.ovL.create_group(f'{s}') for s in [0,1]]

            from pyscf.pbc.mp.kmp2 import _init_mp_df_eris
            for s in [0,1]:
                _init_mp_df_eris(mymp, mo_coeff[s], mymp.nocc[s], s_ovL[s])

    else:
        fao2mo = mymp._scf.with_df.ao2mo

        def get_ovov(sab, kiajb, i01, j01):
            sa, sb = sab
            ki,ka,kj,kb = kiajb
            i0,i1 = i01
            j0,j1 = j01
            nocci = i1-i0
            noccj = j1-j0

            orbo_i = mo_coeff[sa][ki][:,i0:i1]
            orbo_j = mo_coeff[sb][kj][:,j0:j1]
            orbv_a = mo_coeff[sa][ka][:,nocc[sa]:]
            orbv_b = mo_coeff[sb][kb][:,nocc[sb]:]
            ovov = fao2mo((orbo_i,orbv_a,orbo_j,orbv_b),
                          (kpts[ki],kpts[ka],kpts[kj],kpts[kb]),
                          compact=False) / nkpts
            return ovov.reshape(nocci,nvir[sa],noccj,nvir[sb])

        eris._get_ovov = get_ovov

    log.timer('%s ao2mo'%(mymp.__class__.__name__), *time0)
    return eris


from pyscf.pbc import scf
scf.kuhf.KUHF.MP2 = lib.class_as_method(KUMP2)


if __name__ == '__main__':
    from pyscf.pbc import gto, scf, mp
    from pyscf import gto as molgto, scf as molscf, mp as molmp

    atom = '''
    O          0.00000        0.00000        0.11779
    H          0.00000        0.75545       -0.47116
    H          0.00000       -0.75545       -0.47116
    '''
    basis = 'cc-pvdz'
    a = np.eye(3)*20
    spin0 = 2
    kmesh = [1,1,1]
    nkpts = int(np.prod(kmesh))
    spin = spin0 * nkpts
    frozen = 1

    cell = gto.M(atom=atom, basis=basis, a=a, spin=spin)
    kpts = cell.make_kpts(kmesh)

    mf = scf.KUHF(cell, kpts).rs_density_fit().run()
    mmp = mp.KMP2(mf, frozen=frozen).set(verbose=6).run()

    mol = molgto.M(atom=atom, basis=basis, spin=spin0)
    mfmol = molscf.UHF(mol).density_fit().run()
    mpmol = molmp.MP2(mfmol, frozen=frozen).set(verbose=4).run()

    print('mol pbc difference: %.10f' % (mmp.e_corr-mpmol.e_corr))

    # compare to KRHF
    cell = gto.M(atom=atom, basis=basis, a=a)
    kmesh = [2,1,1]
    kpts = cell.make_kpts(kmesh)
    nkpts = len(kpts)

    rmf = scf.KRHF(cell, kpts).rs_density_fit().run()
    rmmp = mp.KMP2(rmf, frozen=frozen).set(verbose=6).run()
    kdm1 = rmmp.make_rdm1()
    kdm2 = rmmp.make_rdm2()

    # copy the spin-restricted SCF solution
    mf = scf.KUHF(cell, kpts).rs_density_fit()
    mf.mo_coeff = [rmf.mo_coeff]*2
    mf.mo_occ = [rmf.mo_occ]*2
    mf.mo_energy = [rmf.mo_energy]*2
    mf.e_tot = rmf.e_tot
    mf.converged = True
    mmp = mp.KMP2(mf, frozen=frozen).set(verbose=6).run()
    skdm1 = mmp.make_rdm1()
    skdm2 = mmp.make_rdm2()
    kdm1u = [dm0+dm1 for dm0,dm1 in zip(skdm1[0],skdm1[1])]
    kdm2u = np.ndarray((nkpts,nkpts,nkpts), dtype=object)
    for k1 in range(nkpts):
        for k2 in range(nkpts):
            for k3 in range(nkpts):
                k4 = mmp.khelper.kconserv[k1, k2, k3]
                kdm2u[k1,k2,k3] = (skdm2[0][k1][k2][k3] + skdm2[2][k1][k2][k3] +
                                   skdm2[1][k1][k2][k3] + skdm2[1][k3][k4][k1].transpose(2,3,0,1))

    nocc = rmmp.nocc
    k = 0
    for dm,dmu in zip(kdm1,kdm1u):
        print(f'k = {k}')
        print('dmoo err:', abs(dm[:nocc,:nocc]-dmu[:nocc,:nocc]).max())
        print('dmvv err:', abs(dm[nocc:,nocc:]-dmu[nocc:,nocc:]).max())
        print()
        k += 1

    for k1 in range(nkpts):
        for k2 in range(nkpts):
            for k3 in range(nkpts):
                print(f'ks = {k1} {k2} {k3}')
                print('dm2  err:', abs(kdm2[k1,k2,k3]-kdm2u[k1,k2,k3]).max())
                print()

    print('krmp2 kump2 difference: %.10f' % (rmmp.e_corr-mmp.e_corr))
